const WORDS = [
  {en:"apple", th:"แอปเปิล; ผลไม้"},
  {en:"book", th:"หนังสือ"},
  {en:"cat", th:"แมว"},
  {en:"dog", th:"สุนัข"},
  {en:"food", th:"อาหาร"},
  {en:"water", th:"น้ำ"},
  {en:"house", th:"บ้าน"},
  {en:"car", th:"รถยนต์"},
  {en:"school", th:"โรงเรียน"},
  {en:"teacher", th:"ครู"},
  {en:"student", th:"นักเรียน"},
  {en:"table", th:"โต๊ะ"},
  {en:"chair", th:"เก้าอี้"},
  {en:"pen", th:"ปากกา"},
  {en:"pencil", th:"ดินสอ"},
  {en:"banana", th:"กล้วย"},
  {en:"orange", th:"ส้ม"},
  {en:"grape", th:"องุ่น"},
  {en:"milk", th:"นม"},
  {en:"juice", th:"น้ำผลไม้"},
  {en:"coffee", th:"กาแฟ"},
  {en:"tea", th:"ชา"},
  {en:"bread", th:"ขนมปัง"},
  {en:"rice", th:"ข้าว"},
  {en:"egg", th:"ไข่"},
  {en:"chicken", th:"ไก่"},
  {en:"beef", th:"เนื้อวัว"},
  {en:"pork", th:"หมู"},
  {en:"fish", th:"ปลา"},
  {en:"carrot", th:"แครอท"},
  {en:"tomato", th:"มะเขือเทศ"},
  {en:"potato", th:"มันฝรั่ง"},
  {en:"lettuce", th:"ผักกาด"},
  {en:"sun", th:"ดวงอาทิตย์"},
  {en:"moon", th:"ดวงจันทร์"},
  {en:"star", th:"ดาว"},
  {en:"cloud", th:"เมฆ"},
  {en:"rain", th:"ฝน"},
  {en:"snow", th:"หิมะ"},
  {en:"wind", th:"ลม"},
  {en:"sunshine", th:"แดด"},
  {en:"red", th:"แดง"},
  {en:"blue", th:"น้ำเงิน"},
  {en:"green", th:"เขียว"},
  {en:"yellow", th:"เหลือง"},
  {en:"black", th:"ดำ"},
  {en:"white", th:"ขาว"},
  {en:"hot", th:"ร้อน"},
  {en:"cold", th:"หนาว"},
  {en:"big", th:"ใหญ่"},
  {en:"small", th:"เล็ก"},
  {en:"long", th:"ยาว"},
  {en:"short", th:"สั้น"},
  {en:"happy", th:"สุข"},
  {en:"sad", th:"เศร้า"},
  {en:"angry", th:"โกรธ"},
  {en:"afraid", th:"กลัว"},
  {en:"monday", th:"วันจันทร์"},
  {en:"tuesday", th:"วันอังคาร"},
  {en:"wednesday", th:"วันพุธ"},
  {en:"thursday", th:"วันพฤหัสบดี"},
  {en:"friday", th:"วันศุกร์"},
  {en:"saturday", th:"วันเสาร์"},
  {en:"sunday", th:"วันอาทิตย์"},
  {en:"friend", th:"เพื่อน"},
  {en:"family", th:"ครอบครัว"},
  {en:"father", th:"พ่อ"},
  {en:"mother", th:"แม่"},
  {en:"brother", th:"พี่ชาย/น้องชาย"},
  {en:"sister", th:"พี่สาว/น้องสาว"},
  {en:"baby", th:"เด็กทารก"},
  {en:"man", th:"ผู้ชาย"},
  {en:"woman", th:"ผู้หญิง"},
  {en:"child", th:"เด็ก"},
  {en:"doctor", th:"แพทย์"},
  {en:"nurse", th:"พยาบาล"},
  {en:"police", th:"ตำรวจ"},
  {en:"fireman", th:"นักดับเพลิง"},
  {en:"shop", th:"ร้านค้า"},
  {en:"market", th:"ตลาด"},
  {en:"supermarket", th:"ซูเปอร์มาร์เก็ต"},
  {en:"hospital", th:"โรงพยาบาล"},
  {en:"bank", th:"ธนาคาร"},
  {en:"post office", th:"ที่ทำการไปรษณีย์"},
  {en:"library", th:"ห้องสมุด"},
  {en:"park", th:"สวนสาธารณะ"},
  {en:"bus", th:"รถบัส"},
  {en:"train", th:"รถไฟ"},
  {en:"plane", th:"เครื่องบิน"},
  {en:"boat", th:"เรือ"},
  {en:"bicycle", th:"จักรยาน"},
  {en:"motorbike", th:"มอเตอร์ไซค์"},
  {en:"road", th:"ถนน"},
  {en:"street", th:"ถนน"},
  {en:"bridge", th:"สะพาน"},
  {en:"river", th:"แม่น้ำ"},
  {en:"mountain", th:"ภูเขา"},
  {en:"sea", th:"ทะเล"},
  {en:"lake", th:"ทะเลสาบ"},
  {en:"tree", th:"ต้นไม้"},
  {en:"flower", th:"ดอกไม้"},
  {en:"grass", th:"หญ้า"},
  {en:"leaf", th:"ใบไม้"},
  {en:"sky", th:"ท้องฟ้า"},
  {en:"earth", th:"โลก"},
  {en:"storm", th:"พายุ"},
  {en:"ice", th:"น้ำแข็ง"},
  {en:"fruit", th:"ผลไม้"},
  {en:"vegetable", th:"ผัก"},
  {en:"meat", th:"เนื้อสัตว์"},
  {en:"noodle", th:"ก๋วยเตี๋ยว"},
  {en:"soup", th:"ซุป"},
  {en:"cake", th:"เค้ก"},
  {en:"cookie", th:"คุกกี้"},
  {en:"chocolate", th:"ช็อกโกแลต"},
  {en:"ice cream", th:"ไอศกรีม"},
  {en:"drink", th:"เครื่องดื่ม"},
  {en:"shirt", th:"เสื้อ"},
  {en:"pants", th:"กางเกง"},
  {en:"skirt", th:"กระโปรง"},
  {en:"dress", th:"ชุดเดรส"},
  {en:"shoe", th:"รองเท้า"},
  {en:"sock", th:"ถุงเท้า"},
  {en:"hat", th:"หมวก"},
  {en:"glove", th:"ถุงมือ"},
  {en:"bag", th:"กระเป๋า"},
  {en:"wallet", th:"กระเป๋าสตางค์"},
  {en:"belt", th:"เข็มขัด"},
  {en:"watch", th:"นาฬิกา"},
  {en:"ring", th:"แหวน"},
  {en:"necklace", th:"สร้อยคอ"},
  {en:"earring", th:"ต่างหู"},
  {en:"phone", th:"โทรศัพท์"},
  {en:"computer", th:"คอมพิวเตอร์"},
  {en:"laptop", th:"แล็ปท็อป"},
  {en:"tablet", th:"แท็บเล็ต"},
  {en:"camera", th:"กล้อง"},
  {en:"television", th:"โทรทัศน์"},
  {en:"radio", th:"วิทยุ"},
  {en:"music", th:"ดนตรี"},
  {en:"song", th:"เพลง"},
  {en:"movie", th:"ภาพยนตร์"},
  {en:"game", th:"เกม"},
  {en:"sport", th:"กีฬา"},
  {en:"football", th:"ฟุตบอล"},
  {en:"basketball", th:"บาสเกตบอล"},
  {en:"tennis", th:"เทนนิส"},
  {en:"swim", th:"ว่ายน้ำ"},
  {en:"run", th:"วิ่ง"},
  {en:"walk", th:"เดิน"},
  {en:"jump", th:"กระโดด"},
  {en:"dance", th:"เต้นรำ"},
  {en:"sing", th:"ร้องเพลง"},
  {en:"read", th:"อ่าน"},
  {en:"write", th:"เขียน"},
  {en:"listen", th:"ฟัง"},
  {en:"speak", th:"พูด"},
  {en:"sleep", th:"นอน"},
  {en:"wake", th:"ตื่น"},
  {en:"sit", th:"นั่ง"},
  {en:"stand", th:"ยืน"},
  {en:"open", th:"เปิด"},
  {en:"close", th:"ปิด"},
  {en:"buy", th:"ซื้อ"},
  {en:"sell", th:"ขาย"},
  {en:"pay", th:"จ่าย"},
  {en:"eat", th:"กิน"},
  {en:"drink", th:"ดื่ม"},
  {en:"cook", th:"ทำอาหาร"},
  {en:"clean", th:"ทำความสะอาด"},
  {en:"wash", th:"ล้าง"},
  {en:"cut", th:"ตัด"},
  {en:"build", th:"สร้าง"},
  {en:"draw", th:"วาด"},
  {en:"paint", th:"ระบายสี"},
  {en:"drive", th:"ขับรถ"},
  {en:"fly", th:"บิน"},
  {en:"ride", th:"ขี่"},
  {en:"climb", th:"ปีน"},
  {en:"play", th:"เล่น"},
  {en:"study", th:"ศึกษา"},
  {en:"teach", th:"สอน"},
  {en:"learn", th:"เรียนรู้"},
  {en:"think", th:"คิด"},
  {en:"know", th:"รู้"},
  {en:"understand", th:"เข้าใจ"},
  {en:"remember", th:"จำ"},
  {en:"forget", th:"ลืม"},
  {en:"love", th:"รัก"},
  {en:"like", th:"ชอบ"},
  {en:"hate", th:"เกลียด"},
  {en:"want", th:"ต้องการ"},
  {en:"need", th:"จำเป็นต้องมี"},
  {en:"help", th:"ช่วย"},
  {en:"ask", th:"ถาม"},
  {en:"answer", th:"ตอบ"},
  {en:"call", th:"โทร"},
  {en:"send", th:"ส่ง"},
  {en:"receive", th:"รับ"},
  {en:"wait", th:"รอ"},
  {en:"start", th:"เริ่ม"},
  {en:"finish", th:"จบ"},
  {en:"push", th:"ดัน"},
  {en:"pull", th:"ดึง"},
  {en:"turn", th:"หมุน"},
  {en:"move", th:"เคลื่อนที่"},
  {en:"stop", th:"หยุด"},
  {en:"go", th:"ไป"},
  {en:"come", th:"มา"},
  {en:"bring", th:"นำมา"},
  {en:"take", th:"เอาไป"},
  {en:"give", th:"ให้"},
  {en:"cat", th:"แมว"},
  {en:"dog", th:"สุนัข"},
  {en:"bird", th:"นก"},
  {en:"fish", th:"ปลา"},
  {en:"horse", th:"ม้า"},
  {en:"cow", th:"วัว"},
  {en:"pig", th:"หมู"},
  {en:"sheep", th:"แกะ"},
  {en:"goat", th:"แพะ"},
  {en:"chicken", th:"ไก่"},
  {en:"duck", th:"เป็ด"},
  {en:"rabbit", th:"กระต่าย"},
  {en:"tiger", th:"เสือ"},
  {en:"lion", th:"สิงโต"},
  {en:"bear", th:"หมี"},
  {en:"elephant", th:"ช้าง"},
  {en:"monkey", th:"ลิง"},
  {en:"snake", th:"งู"},
  {en:"frog", th:"กบ"},
  {en:"bee", th:"ผึ้ง"},
  {en:"ant", th:"มด"},
  {en:"spider", th:"แมงมุม"},
  {en:"butterfly", th:"ผีเสื้อ"},
  {en:"flower", th:"ดอกไม้"},
  {en:"tree", th:"ต้นไม้"},
  {en:"leaf", th:"ใบไม้"},
  {en:"grass", th:"หญ้า"},
  {en:"water", th:"น้ำ"},
  {en:"river", th:"แม่น้ำ"},
  {en:"lake", th:"ทะเลสาบ"},
  {en:"sea", th:"ทะเล"},
  {en:"ocean", th:"มหาสมุทร"},
  {en:"mountain", th:"ภูเขา"},
  {en:"hill", th:"เนินเขา"},
  {en:"valley", th:"หุบเขา"},
  {en:"forest", th:"ป่า"},
  {en:"desert", th:"ทะเลทราย"},
  {en:"island", th:"เกาะ"},
  {en:"beach", th:"ชายหาด"},
  {en:"sand", th:"ทราย"},
  {en:"rock", th:"หิน"},
  {en:"stone", th:"ก้อนหิน"},
  {en:"sun", th:"ดวงอาทิตย์"},
  {en:"moon", th:"ดวงจันทร์"},
  {en:"star", th:"ดาว"},
  {en:"sky", th:"ท้องฟ้า"},
  {en:"cloud", th:"เมฆ"},
  {en:"rain", th:"ฝน"},
  {en:"snow", th:"หิมะ"},
  {en:"wind", th:"ลม"},
  {en:"storm", th:"พายุ"},
  {en:"weather", th:"สภาพอากาศ"},
  {en:"hot", th:"ร้อน"},
  {en:"cold", th:"หนาว"},
  {en:"warm", th:"อบอุ่น"},
  {en:"cool", th:"เย็นสบาย"},
  {en:"spring", th:"ฤดูใบไม้ผลิ"},
  {en:"summer", th:"ฤดูร้อน"},
  {en:"autumn", th:"ฤดูใบไม้ร่วง"},
  {en:"winter", th:"ฤดูหนาว"},
  {en:"morning", th:"เช้า"},
  {en:"afternoon", th:"บ่าย"},
  {en:"evening", th:"เย็น"},
  {en:"night", th:"กลางคืน"},
  {en:"today", th:"วันนี้"},
  {en:"yesterday", th:"เมื่อวาน"},
  {en:"tomorrow", th:"พรุ่งนี้"},
  {en:"week", th:"สัปดาห์"},
  {en:"month", th:"เดือน"},
  {en:"year", th:"ปี"},
  {en:"time", th:"เวลา"},
  {en:"hour", th:"ชั่วโมง"},
  {en:"minute", th:"นาที"},
  {en:"second", th:"วินาที"},
  {en:"day", th:"วัน"},
  {en:"night", th:"กลางคืน"},
  {en:"breakfast", th:"อาหารเช้า"},
  {en:"lunch", th:"อาหารกลางวัน"},
  {en:"dinner", th:"อาหารเย็น"},
  {en:"meal", th:"มื้ออาหาร"},
  {en:"drink", th:"เครื่องดื่ม"},
  {en:"water", th:"น้ำ"},
  {en:"tea", th:"ชา"},
  {en:"coffee", th:"กาแฟ"},
  {en:"juice", th:"น้ำผลไม้"},
  {en:"milk", th:"นม"},
  {en:"sugar", th:"น้ำตาล"},
  {en:"salt", th:"เกลือ"},
  {en:"pepper", th:"พริกไทย"},
  {en:"bread", th:"ขนมปัง"},
  {en:"rice", th:"ข้าว"},
  {en:"noodle", th:"ก๋วยเตี๋ยว"},
  {en:"egg", th:"ไข่"},
  {en:"meat", th:"เนื้อสัตว์"},
  {en:"chicken", th:"ไก่"},
  {en:"beef", th:"เนื้อวัว"},
  {en:"pork", th:"หมู"},
  {en:"fish", th:"ปลา"},
  {en:"fruit", th:"ผลไม้"},
  {en:"vegetable", th:"ผัก"},
  {en:"apple", th:"แอปเปิล"},
  {en:"banana", th:"กล้วย"},
  {en:"orange", th:"ส้ม"},
  {en:"grape", th:"องุ่น"},
  {en:"lemon", th:"มะนาว"},
  {en:"mango", th:"มะม่วง"},
  {en:"pear", th:"ลูกแพร์"},
  {en:"peach", th:"พีช"},
  {en:"cherry", th:"เชอร์รี่"},
  {en:"strawberry", th:"สตรอว์เบอร์รี่"},
  {en:"school", th:"โรงเรียน"},
  {en:"class", th:"ชั้นเรียน"},
  {en:"student", th:"นักเรียน"},
  {en:"teacher", th:"ครู"},
  {en:"lesson", th:"บทเรียน"},
  {en:"homework", th:"การบ้าน"},
  {en:"exam", th:"การสอบ"},
  {en:"test", th:"แบบทดสอบ"},
  {en:"subject", th:"วิชา"},
  {en:"math", th:"คณิตศาสตร์"},
  {en:"english", th:"ภาษาอังกฤษ"},
  {en:"science", th:"วิทยาศาสตร์"},
  {en:"history", th:"ประวัติศาสตร์"},
  {en:"geography", th:"ภูมิศาสตร์"},
  {en:"art", th:"ศิลปะ"},
  {en:"music", th:"ดนตรี"},
  {en:"sport", th:"กีฬา"},
  {en:"library", th:"ห้องสมุด"},
  {en:"book", th:"หนังสือ"},
  {en:"pen", th:"ปากกา"},
  {en:"pencil", th:"ดินสอ"},
  {en:"paper", th:"กระดาษ"},
  {en:"notebook", th:"สมุด"},
  {en:"bag", th:"กระเป๋า"},
  {en:"chair", th:"เก้าอี้"},
  {en:"table", th:"โต๊ะ"},
  {en:"computer", th:"คอมพิวเตอร์"},
  {en:"laptop", th:"แล็ปท็อป"},
  {en:"phone", th:"โทรศัพท์"},
  {en:"clock", th:"นาฬิกา"},
  {en:"calendar", th:"ปฏิทิน"},
  {en:"room", th:"ห้อง"},
  {en:"building", th:"อาคาร"},
  {en:"schoolbag", th:"กระเป๋านักเรียน"},
  {en:"blackboard", th:"กระดานดำ"},
  {en:"whiteboard", th:"กระดานขาว"},
  {en:"marker", th:"ปากกาเมจิก"},
  {en:"eraser", th:"ยางลบ"},
  {en:"ruler", th:"ไม้บรรทัด"},
  {en:"scissors", th:"กรรไกร"},
  {en:"glue", th:"กาว"},
  {en:"paint", th:"สี"},
  {en:"brush", th:"พู่กัน"},
  {en:"crayon", th:"สีเทียน"},
  {en:"music", th:"ดนตรี"},
  {en:"sing", th:"ร้องเพลง"},
  {en:"dance", th:"เต้นรำ"},
  {en:"play", th:"เล่น"},
  {en:"sport", th:"กีฬา"},
  {en:"football", th:"ฟุตบอล"},
  {en:"basketball", th:"บาสเกตบอล"},
  {en:"tennis", th:"เทนนิส"},
  {en:"swim", th:"ว่ายน้ำ"},
  {en:"run", th:"วิ่ง"},
  {en:"walk", th:"เดิน"},
  {en:"jump", th:"กระโดด"},
  {en:"read", th:"อ่าน"},
  {en:"write", th:"เขียน"},
  {en:"listen", th:"ฟัง"},
  {en:"speak", th:"พูด"},
  {en:"learn", th:"เรียนรู้"},
  {en:"teach", th:"สอน"},
  {en:"study", th:"ศึกษา"},
  {en:"think", th:"คิด"},
  {en:"know", th:"รู้"},
  {en:"understand", th:"เข้าใจ"},
  {en:"remember", th:"จำ"},
  {en:"forget", th:"ลืม"},
  {en:"help", th:"ช่วย"},
  {en:"ask", th:"ถาม"},
  {en:"answer", th:"ตอบ"},
  {en:"call", th:"โทร"},
  {en:"send", th:"ส่ง"},
  {en:"receive", th:"รับ"},
  {en:"buy", th:"ซื้อ"},
  {en:"sell", th:"ขาย"},
  {en:"pay", th:"จ่าย"},
  {en:"eat", th:"กิน"},
  {en:"drink", th:"ดื่ม"},
  {en:"cook", th:"ทำอาหาร"},
  {en:"clean", th:"ทำความสะอาด"},
  {en:"wash", th:"ล้าง"},
  {en:"cut", th:"ตัด"},
  {en:"build", th:"สร้าง"},
  {en:"draw", th:"วาด"},
  {en:"paint", th:"ระบายสี"},
  {en:"drive", th:"ขับรถ"},
  {en:"fly", th:"บิน"},
  {en:"ride", th:"ขี่"},
  {en:"climb", th:"ปีน"},
  {en:"move", th:"เคลื่อนที่"},
  {en:"stop", th:"หยุด"},
  {en:"go", th:"ไป"},
  {en:"come", th:"มา"},
  {en:"bring", th:"นำมา"},
  {en:"take", th:"เอาไป"},
  {en:"give", th:"ให้"},
  {en:"love", th:"รัก"},
  {en:"like", th:"ชอบ"},
  {en:"hate", th:"เกลียด"},
  {en:"want", th:"ต้องการ"},
  {en:"need", th:"จำเป็นต้องมี"},
  {en:"think", th:"คิด"},
  {en:"know", th:"รู้"},
  {en:"understand", th:"เข้าใจ"},
  {en:"remember", th:"จำ"},
  {en:"forget", th:"ลืม"},
  {en:"play", th:"เล่น"},
  {en:"work", th:"ทำงาน"},
  {en:"study", th:"ศึกษา"},
  {en:"teach", th:"สอน"},
  {en:"learn", th:"เรียนรู้"},
  {en:"read", th:"อ่าน"},
  {en:"write", th:"เขียน"},
  {en:"listen", th:"ฟัง"},
  {en:"speak", th:"พูด"},
  {en:"watch", th:"ดู"},
  {en:"look", th:"มอง"},
  {en:"see", th:"เห็น"},
  {en:"hear", th:"ได้ยิน"},
  {en:"smell", th:"ได้กลิ่น"},
  {en:"touch", th:"สัมผัส"},
  {en:"taste", th:"ชิม"},
  {en:"walk", th:"เดิน"},
  {en:"run", th:"วิ่ง"},
  {en:"jump", th:"กระโดด"},
  {en:"climb", th:"ปีน"},
  {en:"swim", th:"ว่ายน้ำ"},
  {en:"dance", th:"เต้นรำ"},
  {en:"sing", th:"ร้องเพลง"},
  {en:"sleep", th:"นอน"},
  {en:"wake", th:"ตื่น"},
  {en:"sit", th:"นั่ง"},
  {en:"stand", th:"ยืน"},
  {en:"open", th:"เปิด"},
  {en:"close", th:"ปิด"},
  {en:"push", th:"ดัน"},
  {en:"pull", th:"ดึง"},
  {en:"turn", th:"หมุน"},
  {en:"start", th:"เริ่ม"},
  {en:"finish", th:"จบ"},
  {en:"wait", th:"รอ"},
  {en:"call", th:"โทร"},
  {en:"send", th:"ส่ง"},
  {en:"receive", th:"รับ"},
  {en:"help", th:"ช่วย"},
  {en:"ask", th:"ถาม"},
  {en:"answer", th:"ตอบ"},
  {en:"buy", th:"ซื้อ"},
  {en:"sell", th:"ขาย"},
  {en:"pay", th:"จ่าย"},
  {en:"eat", th:"กิน"},
  {en:"drink", th:"ดื่ม"},
  {en:"cook", th:"ทำอาหาร"},
  {en:"clean", th:"ทำความสะอาด"},
  {en:"wash", th:"ล้าง"},
  {en:"cut", th:"ตัด"}
);


// ====== ตัวแปร ======
let currentIndex = 0;
let score = localStorage.getItem("score") ? parseInt(localStorage.getItem("score")) : 0;

// ====== Element ======
const wordEl = document.getElementById("word");
const meaningEl = document.getElementById("meaning");
const showBtn = document.getElementById("show-meaning");
const nextBtn = document.getElementById("next-word");

const quizQuestion = document.getElementById("quiz-question");
const quizOptions = document.getElementById("quiz-options");

const scoreEl = document.getElementById("score");
const rankEl = document.getElementById("rank");

// ====== ฟังก์ชัน Flashcard ======
function showWord() {
  const word = words[currentIndex];
  wordEl.textContent = word.en;
  meaningEl.textContent = word.th;
  meaningEl.style.display = "none";
  loadQuiz();
}

showBtn.addEventListener("click", () => {
  meaningEl.style.display = "block";
});

nextBtn.addEventListener("click", () => {
  currentIndex = Math.floor(Math.random() * words.length);
  showWord();
});

// ====== ฟังก์ชัน Quiz ======
function loadQuiz() {
  const word = words[currentIndex];
  quizQuestion.textContent = `คำแปลของ "${word.en}" คือ?`;

  let options = [word.th];
  while (options.length < 4) {
    const random = words[Math.floor(Math.random() * words.length)].th;
    if (!options.includes(random)) options.push(random);
  }

  options.sort(() => Math.random() - 0.5);
  quizOptions.innerHTML = "";

  options.forEach(opt => {
    const btn = document.createElement("button");
    btn.textContent = opt;
    btn.addEventListener("click", () => checkAnswer(opt, word.th));
    quizOptions.appendChild(btn);
  });
}

function checkAnswer(selected, correct) {
  if (selected === correct) {
    score += 50;
    alert("ถูกต้อง! +50 คะแนน");
  } else {
    alert("ผิด! คำตอบคือ: " + correct);
  }
  updateScoreAndRank();
  localStorage.setItem("score", score);
}

// ====== ฟังก์ชันคะแนนและแรงค์ ======
function updateScoreAndRank() {
  scoreEl.textContent = score;
  let rank = "";
  if(score < 100) rank = "Beginner";
  else if(score < 200) rank = "Learner";
  else if(score < 300) rank = "Intermediate";
  else if(score < 400) rank = "Advanced";
  else rank = "Expert";
  rankEl.textContent = rank;
}

// ====== เริ่มต้น ======
showWord();
updateScoreAndRank();
